### ISSUE TITLE
Calling function 'makeDecorator', function calls are not supported. 

### ISSUE THREAD

**Issue by Thijmenw** [Durwella/zoomable-canvas#1]
By building android --prod the plugin is giving this issue:

`
[11:40:44]  build prod started ... 
[11:40:44]  clean started ... 
[11:40:44]  clean finished in 1 ms 
[11:40:44]  copy started ... 
[11:40:44]  deeplinks started ... 
[11:40:45]  deeplinks finished in 227 ms 
[11:40:45]  ngc started ... 
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /home/thijmen/Desktop/abk/node_modules/@durwella/zoomable-canvas/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /home/thijmen/Desktop/abk/node_modules/@durwella/zoomable-canvas/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /home/thijmen/Desktop/abk/node_modules/@durwella/zoomable-canvas/node_modules/@angular/core/src/di/opaque_token.d.ts
    at Error (native)
    at syntaxError (/home/thijmen/Desktop/abk/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at simplifyInContext (/home/thijmen/Desktop/abk/node_modules/@angular/compiler/bundles/compiler.umd.js:23870:23)
    at StaticReflector.simplify (/home/thijmen/Desktop/abk/node_modules/@angular/compiler/bundles/compiler.umd.js:23882:13)
    at StaticReflector.annotations (/home/thijmen/Desktop/abk/node_modules/@angular/compiler/bundles/compiler.umd.js:23331:41)
    at NgModuleResolver.resolve (/home/thijmen/Desktop/abk/node_modules/@angular/compiler/bundles/compiler.umd.js:13883:70)
    at CompileMetadataResolver.getNgModuleMetadata (/home/thijmen/Desktop/abk/node_modules/@angular/compiler/bundles/compiler.umd.js:14473:60)
    at addNgModule (/home/thijmen/Desktop/abk/node_modules/@angular/compiler/bundles/compiler.umd.js:23050:58)
    at /home/thijmen/Desktop/abk/node_modules/@angular/compiler/bundles/compiler.umd.js:23061:14
    at Array.forEach (native)
`

**Comment by wlmiller** [comment]
Thanks @Thijmenw for your report - I believe I've fixed this error in the most recent version of the package on npm (1.1.0).
